### ISSUE TITLE
ValueError: probabilities contain NaN

### ISSUE THREAD

**Issue by XieTianLi** [benedekrozemberczki/GAM#15]
Hi, thank you very much for your excellent work, I created my own dataset following the .json file format in your code, I had this problem after training part of my data, I observed the difference between our data, there is a non-connected graph in my data and there are isolated nodes, is this the reason why the code is wrong in the middle of training?
Training started.

Epoch:   0%|          | 0/10 [00:00<?, ?it/s]
  0%|          | 0/25 [00:00<?, ?it/s]
(Loss=4.1643):   0%|          | 0/25 [00:01<?, ?it/s]
(Loss=4.1643):   4%|▍         | 1/25 [00:01<00:29,  1.22s/it]
(Loss=1.1765):   4%|▍         | 1/25 [00:02<00:29,  1.22s/it]
(Loss=1.1765):   8%|▊         | 2/25 [00:02<00:28,  1.26s/it]
(Loss=-1.8768):   8%|▊         | 2/25 [00:03<00:28,  1.26s/it]
(Loss=-1.8768):  12%|█▏        | 3/25 [00:03<00:26,  1.20s/it]
(Loss=-1.1337):  12%|█▏        | 3/25 [00:04<00:26,  1.20s/it]
(Loss=-1.1337):  16%|█▌        | 4/25 [00:05<00:26,  1.27s/it]
Epoch:   0%|          | 0/10 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "D:/GAM-master/src/main.py", line 19, in <module>
    main()
  File "D:/GAM-master/src/main.py", line 14, in main
    model.fit()
  File "D:\GAM-master\src\gam.py", line 272, in fit
    self.epoch_loss = self.epoch_loss + self.process_batch(batches[batch])
  File "D:\GAM-master\src\gam.py", line 240, in process_batch
    batch_loss = self.process_graph(graph_path, batch_loss)
  File "D:\GAM-master\src\gam.py", line 221, in process_graph
    predictions, node, attention_score = self.model(data, graph, features, node)
  File "D:\anaconda\envs\spyder\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\GAM-master\src\gam.py", line 180, in forward
    self.state, node, attention_score = self.step_block(data, graph, features, node)
  File "D:\anaconda\envs\spyder\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\GAM-master\src\gam.py", line 97, in forward
    feature_row, node, attention_score = self.make_step(node, graph, features,
  File "D:\GAM-master\src\gam.py", line 78, in make_step
    label = self.sample_node_label(orig_neighbors, graph, features)
  File "D:\GAM-master\src\gam.py", line 66, in sample_node_label
    label = np.random.choice(np.arange(len(self.identifiers)), p=normalized_attention_spread)
  File "mtrand.pyx", line 928, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN

Process finished with exit code 1

Here's an example from my .json file
{"target": 1,"edges":[[0,2],[0,8],[0,12],[0,13],[0,14],[1,2],[1,8],[2,3],[2,8],[3,5],[6,14],[11,12],[11,13]],"labels":{"0":113,"1":106,"2":78,"3":102,"4":91,"5":63,"6":68,"7":76,"8":73,"9":119,"10":87,"11":102,"12":110,"13":117,"14":78,"15":124},"inverse_labels":{"113":[0],"106":[1],"78":[2,14],"102":[3,11],"91":[4],"63":[5],"68":[6],"76":[7],"73":[8],"119":[9],"87":[10],"110":[12],"117":[13],"124":[15]}}

Sorry for disturbing you, thank you very much for your help !

**Comment by XieTianLi** [comment]
During the debugging, I found that the element Nan appeared when the data was trained：{"target": 0,"edges":[[0,1],[0,2],[0,3],[0,4],[0,5],[0,6],[0,7],[0,10],[0,11],[0,12],[0,13],[0,14],[1,2],[1,3],[1,4],[1,6],[1,7],[1,8],[1,14],[2,3],[2,4],[2,5],[2,6],[2,7],[2,10],[2,11],[2,12],[2,13],[2,14],[2,15],[3,5],[3,6],[3,7],[3,8],[3,9],[3,12],[3,13],[3,14],[3,15],[4,5],[4,6],[4,7],[4,9],[4,11],[5,6],[5,13],[6,7],[6,14],[7,8],[7,12],[7,13],[8,9],[8,10],[8,12],[8,13],[8,15],[9,10],[9,11],[9,14],[10,14],[11,15],[12,14],[13,14],[14,15]],"labels":{"0":506,"1":1370,"2":490,"3":494,"4":344,"5":546,"6":854,"7":794,"8":357,"9":618,"10":280,"11":343,"12":562,"13":754,"14":427,"15":884},"inverse_labels":{"506":[0],"1370":[1],"490":[2],"494":[3],"344":[4],"546":[5],"854":[6],"794":[7],"357":[8],"618":[9],"280":[10],"343":[11],"562":[12],"754":[13],"427":[14],"884":[15]}}
![image](https://user-images.githubusercontent.com/61816674/115717669-f8df0580-a3ac-11eb-9e05-05d983dbf94e.png)

**Comment by XieTianLi** [comment]
During the debugging, I found that the element Nan appeared when the data was trained：{"target": 0,"edges":[[0,1],[0,4],[0,5],[0,9],[0,13],[0,14],[0,15],[1,3],[1,4],[1,5],[1,6],[1,7],[1,8],[1,9],[1,10],[1,11],[1,12],[1,13],[1,15],[2,3],[2,6],[2,7],[2,8],[2,9],[2,10],[2,11],[2,13],[2,14],[2,15],[3,5],[3,6],[3,7],[3,8],[3,11],[3,12],[3,14],[3,15],[4,5],[4,14],[4,15],[5,6],[5,7],[5,8],[5,9],[5,10],[5,11],[5,12],[5,13],[5,15],[6,8],[6,9],[6,10],[6,11],[6,12],[6,13],[6,14],[6,15],[7,8],[7,9],[7,10],[7,13],[7,14],[7,15],[8,9],[8,10],[8,11],[8,12],[8,13],[8,15],[9,10],[9,11],[9,14],[9,15],[10,11],[10,12],[10,14],[10,15],[11,13],[11,14],[11,15],[12,14],[12,15],[13,14],[14,15]],"labels":{"0":445,"1":1527,"2":986,"3":811,"4":624,"5":980,"6":522,"7":867,"8":746,"9":798,"10":312,"11":429,"12":303,"13":539,"14":365,"15":386},"inverse_labels":{"445":[0],"1527":[1],"986":[2],"811":[3],"624":[4],"980":[5],"522":[6],"867":[7],"746":[8],"798":[9],"312":[10],"429":[11],"303":[12],"539":[13],"365":[14],"386":[15]}}
![image](https://user-images.githubusercontent.com/61816674/115718231-815da600-a3ad-11eb-9ac3-d135de8e3949.png)

**Comment by XieTianLi** [comment]
I’ve been debugging it for a long time, I really need your help, your help will solve my huge confusion.
Best !
