### ISSUE TITLE
Unhashable type dict

### ISSUE THREAD

**Issue by acecreamu** [benedekrozemberczki/GAM#3]
I tried to run the code with default parameters and dataset, and on different systems I got the same error:

```
Epoch:   0%|                                                                                    | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):                                                                | 0/2 [00:00<?, ?it/s]
  File "src/main.py", line 17, in <module>
    main()
  File "src/main.py", line 12, in main
    model.fit()
  File "C:\Users\acecreamu\GAM\src\gam.py", line 251, in fit
    self.epoch_loss = self.epoch_loss + self.process_batch(batches[batch])
  File "C:\Users\acecreamu\GAM\src\gam.py", line 221, in process_batch
    batch_loss = self.process_graph(graph_path, batch_loss)
  File "C:\Users\acecreamu\GAM\src\gam.py", line 202, in process_graph
    predictions, node, attention_score = self.model(data, graph, features, node)
  File "C:\Users\acecreamu\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\acecreamu\GAM\src\gam.py", line 166, in forward
    self.state, node, attention_score = self.step_block(data, graph, features, node)
  File "C:\Users\acecreamu\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\acecreamu\GAM\src\gam.py", line 88, in forward
    feature_row, node, attention_score = self.make_step(node, graph, features, data["labels"], data["inverse_labels"])
  File "C:\Users\acecreamu\GAM\src\gam.py", line 69, in make_step
    original_neighbors = set(nx.neighbors(graph, node))
  File "C:\Users\acecreamu\Anaconda3\lib\site-packages\networkx\classes\function.py", line 64, in neighbors
    return G.neighbors(n)
  File "C:\Users\acecreamu\Anaconda3\lib\site-packages\networkx\classes\graph.py", line 1266, in neighbors
    return iter(self._adj[n])
TypeError: unhashable type: 'dict'
```

So [the problem](https://stackoverflow.com/questions/13264511/typeerror-unhashable-type-dict) is in line `original_neighbors = set(nx.neighbors(graph, node))` , but I have no clue how to solve it.

**Comment by benedekrozemberczki** [comment]
What is your NX version?

**Comment by acecreamu** [comment]
@benedekrozemberczki 
I tried 2.1 and 2.3. Makes sense now. Everything works fine with 1.11, thank you for help.
