### ISSUE TITLE
ValueError: probabilities contain NaN

### ISSUE THREAD

**Issue by yy1335574510** [benedekrozemberczki/GAM#8]
![image](https://user-images.githubusercontent.com/51071665/60640334-2f0a6880-9e59-11e9-870d-1e5ca9baffbc.png)
This problem occurred when I used my own data set? Why did he happen, how can I solve it, I have turned my data into the same json format as the input folder.

**Comment by benedekrozemberczki** [comment]
Send me your data.

**Comment by yy1335574510** [comment]
ＯＫ，This loss was 2 at the beginning and then dropped to -400

**Comment by yy1335574510** [comment]
Can you use Baidu Cloud to receive my data? Because this data is about 200M.

**Comment by yy1335574510** [comment]
https://drive.google.com/file/d/1N2FHgUZwY6PGULf8JRtqSIZiK3oV39E7/view?usp=sharing

**Comment by yy1335574510** [comment]
The above is my training data, I don't know what happened? Can you help me solve it? Thank you very much if possible

**Comment by yy1335574510** [comment]
I haven't read the paper carefully, but why is this loss function negative? I'm weird!

**Comment by yy1335574510** [comment]
testdata:
https://drive.google.com/file/d/1OvlGMPw5koXKvw_QHOH96aWJ7mUSzF0O/view?usp=sharing

**Comment by yy1335574510** [comment]
How should I solve it? But I regret to find that it didn't help, then it was turned off.

**Comment by XieTianLi** [comment]
Hi, I'm having the same problem, I met this problem after training part of my data, I've observed the difference between our data, my data has a non-connected graph and there are isolated nodes, is this the reason why the code is wrong in the middle of training?

Traceback (most recent call last):
  File "D:/GAM-master/src/main.py", line 19, in <module>
    main()
  File "D:/GAM-master/src/main.py", line 14, in main
    model.fit()
  File "D:\GAM-master\src\gam.py", line 272, in fit
    self.epoch_loss = self.epoch_loss + self.process_batch(batches[batch])
  File "D:\GAM-master\src\gam.py", line 240, in process_batch
    batch_loss = self.process_graph(graph_path, batch_loss)
  File "D:\GAM-master\src\gam.py", line 221, in process_graph
    predictions, node, attention_score = self.model(data, graph, features, node)
  File "D:\anaconda\envs\spyder\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\GAM-master\src\gam.py", line 180, in forward
    self.state, node, attention_score = self.step_block(data, graph, features, node)
  File "D:\anaconda\envs\spyder\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\GAM-master\src\gam.py", line 97, in forward
    feature_row, node, attention_score = self.make_step(node, graph, features,
  File "D:\GAM-master\src\gam.py", line 78, in make_step
    label = self.sample_node_label(orig_neighbors, graph, features)
  File "D:\GAM-master\src\gam.py", line 66, in sample_node_label
    label = np.random.choice(np.arange(len(self.identifiers)), p=normalized_attention_spread)
  File "mtrand.pyx", line 928, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN
